- name: install pip
  apt:
    name: python3-pip
    state: present

- name: pip install docker-py
  pip:
    name:
      - docker
      - docker-compose

- name: run container
  docker_container:
    name: mydata
    image: busybox
    volumes:
      - /data
