- name: install pip
  apt:
    name: python3-pip
    state: present

- name: pip install docker-py
  pip:
    name:
      - docker
      - docker-compose
 
- name: Bash docker
  shell: docker --version
      
- name:  Bash docker-compose
  shell: docker-compose --version
      
- name: run container busybox
  docker_container:
    name: mydata
    image: busybox
    volumes:
      - /data
